FROM python:3.12-slim

RUN pip install --upgrade pip

COPY ./src/shared/requirements.txt ./shared/
COPY ./src/auth/requirements.txt ./auth/

RUN pip install -r shared/requirements.txt && \
    pip install -r auth/requirements.txt

WORKDIR /app

COPY . /app

ENV PYTHONPATH=$PYTHONPATH:/app/src

EXPOSE 8001

CMD ["python", "src/events/main.py"]
