"""empty message

Revision ID: 481a672904ab
Revises: 4c321641164c
Create Date: 2025-04-16 12:32:42.824056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481a672904ab'
down_revision: Union[str, None] = '4c321641164c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_description', sa.String(length=156), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_rating', sa.Integer(), nullable=True),
    sa.Column('task_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_marks_assignee_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
