"""empty message

Revision ID: 48b225ae5231
Revises: 481a672904ab
Create Date: 2025-04-18 18:48:39.288330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b225ae5231'
down_revision: Union[str, None] = '481a672904ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_participants_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meeting_participants_user_id_users')),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id', name=op.f('pk_meeting_participants'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_participants')
    # ### end Alembic commands ###
