"""empty message

Revision ID: 4c321641164c
Revises: 8ede15bf9f15
Create Date: 2025-04-16 09:54:09.564723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c321641164c'
down_revision: Union[str, None] = '8ede15bf9f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f('fk_tasks_assignee_id_users'), 'tasks', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_assignee_id_users'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assignee_id')
    # ### end Alembic commands ###
